name: "Reset demo db"
on:
  schedule:
  - cron: "* */1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@v1
      env:
        super_secret: ${{ secrets.SuperSecret }}
      with:
        url: super_secret
        method: 'POST'
