name: "Reset demo db"
on:
  schedule:
  - cron: "0 1 2 * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Reset demo db
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.DEMO_RESET_URL }}
        method: 'GET'

