name: "Close stale issues"
on:
  schedule:
  - cron: "* */1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://TODO/'
        method: 'POST'
