name: "Reset demo db"
on:
  schedule:
  - cron: "* */1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    env: 
        super_secret: ${{ secrets.SuperSecret }}
    steps:
      - uses: fjogeleit/http-request-action@v1
      - with:
          url: super_secret
          method: 'POST'
